name: KMMBridge-Debug
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  kmmbridgepublish:
    concurrency: "kmmbridgepublish-${{ github.repository }}"
    runs-on: macos-latest
    steps:
      - name: Checkout the repo with tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: touchlab/read-property@0.1
        id: versionPropertyValue
        with:
          file: ./gradle.properties
          property: LIBRARY_VERSION

      - name: Print versionPropertyValue
        id: output
        run: echo "${{ steps.versionPropertyValue.outputs.propVal }}"

      - name: Touchlab Sample Sanity Check (Ignore this for your CI)
        uses: touchlab/sample-group-sanity-check@main

      - name: Apply SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.KMMBRIDGE_SSH_KEY }}

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Cache build tooling
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.konan
          key: ${{ runner.os }}-v4-${{ hashFiles('*.gradle.kts') }}

      - name: Create or Find Artifact Release
        id: devrelease
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          repository: touchlab/KMMBridgeAndroidDevFlowPublish
          token: ${{ secrets.KMMBRIDGE_PAT_SECRET }}
          tag_name: "dev-${{ steps.versionPropertyValue.outputs.propVal }}"

      - name: Build Main
        run: ./gradlew kmmBridgePublish -PENABLE_PUBLISHING=true -PNATIVE_BUILD_TYPE=DEBUG -PGITHUB_ARTIFACT_RELEASE_ID=${{ steps.devrelease.outputs.id }} -PGITHUB_ARTIFACT_IDENTIFIER_NAME=${{ steps.trimcommit.outputs.short }} -PGITHUB_PUBLISH_TOKEN=${{ secrets.KMMBRIDGE_PAT_SECRET }} -PGITHUB_REPO=touchlab/KMMBridgeAndroidDevFlowPublish --no-daemon --info --stacktrace
        env:
          GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"

      - uses: touchlab/ga-push-remote-swift-package@v1.1
        id: push-remote-swift-package
        with:
          commitMessage: "KMP SPM package debug build for ${{ github.ref }}"
          remoteRepo: touchlab/KMMBridgeAndroidDevFlowPublish
          remoteBranch: ${{ github.ref }}